name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: 'Update Submodules'
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: 'Configure'
        run: |
          mkdir -p build
          cmake -B build -DPICO_SDK_PATH=./pico-sdk

      - name: 'Build'
        run: |
          make -C build

      - name: 'Upload binary'
        uses: actions/upload-artifact@v4
        with:
          name: dirtyJtag.uf2
          path: build/dirtyJtag.uf2
          retention-days: 15
