name: "tagged-release"

on:
  push:
    tags:
      - "v*"



jobs:
    release_build:
        name: Build release
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build release
              id: build
              uses: samyarsadat/Pico-Build-Action@v1
              with:
                  source_dir: "."
                  cmake_args: "-DCMAKE_BUILD_TYPE=Debug"

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: workspace_artifacts
                  path: ${{steps.build.outputs.output_dir}}

